// <auto-generated />
namespace IEPAuctionSale.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class wuhu2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wuhu2));
        
        string IMigrationMetadata.Id
        {
            get { return "201609222144487_wuhu-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
