CREATE TABLE Auction(
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	ProductName VARCHAR(50) NOT NULL,
	Duration INTEGER NOT NULL,
	StartingPrice INTEGER NOT NULL,
	CurrentPrice INTEGER,
	CurrentBider nvarchar(128),
	[RowVersion] BINARY(256),
	TimeCreated DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TimeOpened DATETIME,
	TimeClosed DATETIME,
	[State] VARCHAR(10), --"DRAFT", "READY", "OPEN", "SOLD" or "EXPIRED"
	ProductPicture IMAGE,
	CONSTRAINT FK_AuctionAccountId FOREIGN KEY (CurrentBider) REFERENCES AspNetUsers(Id) ON DELETE CASCADE ON UPDATE CASCADE,
);

CREATE TABLE Bid(
	AccountId NVARCHAR(128) NOT NULL,
	AuctionId INTEGER NOT NULL,
	TimeBidded DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(AccountId, AuctionId, TimeBidded), 
	CONSTRAINT FK_BidAccountId FOREIGN KEY (AccountId) REFERENCES AspNetUsers(Id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_BidAuctionId FOREIGN KEY (AuctionId) REFERENCES Auction(Id)
);

CREATE TABLE [Order](
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),	
	AccountId NVARCHAR(128) NOT NULL,
	NoTokens INTEGER NOT NULL,
	PriceOfPackage FLOAT NOT NULL,
	TimeOrdered DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FK_OrderAccountId FOREIGN KEY (AccountId) REFERENCES AspNetUsers(Id) ON DELETE CASCADE ON UPDATE CASCADE,
	StatusIndicatior VARCHAR(20) NOT NULL --"PENDING", "CANCELED" or "REALIZED"
);